/* ═══════════════════════════════════════════════
   OSSUARY ATELIER — tools/slang-glossary/script.js
   Client-side dictionary: search, filter, sort, known-word
   tracking (localStorage) and Thai pronunciation.

   The dataset is inlined at build time as window.OA_GLOSSARY
   (see the glossary step in scripts/build.mjs) — there is no
   runtime fetch, so this works from file:// and offline.
   ═══════════════════════════════════════════════ */

(function () {
  'use strict';

  var KNOWN_KEY = 'oa_glossary_known';
  var DEEP_CUT = 4;              /* slanginess >= this counts as a deep cut */
  var DEBOUNCE_MS = 200;

  var CAT_LABELS = {
    'etiquette': 'Etiquette',
    'general-slang': 'General slang',
    'thrift-market': 'Thrift market',
    'skate': 'Skate'
  };

  var grid = document.getElementById('gl-grid');
  if (!grid) return;

  var data = window.OA_GLOSSARY;
  if (!data || !data.entries || !data.entries.length) {
    grid.hidden = true;
    var note = document.createElement('p');
    note.className = 'gl-fail';
    note.textContent =
      'The glossary data failed to load. This page is generated by ' +
      'node scripts/build.mjs --enable-content --steps=glossary.';
    grid.parentNode.insertBefore(note, grid.nextSibling);
    return;
  }

  var entries = data.entries;
  var byId = Object.create(null);
  entries.forEach(function (e) { byId[e.id] = e; });

  var el = {
    q: document.getElementById('gl-q'),
    tabs: document.getElementById('gl-tabs'),
    sort: document.getElementById('gl-sort'),
    deep: document.getElementById('gl-deep'),
    hideKnown: document.getElementById('gl-hide-known'),
    count: document.getElementById('gl-count'),
    empty: document.getElementById('gl-empty'),
    sotd: document.getElementById('gl-sotd-body')
  };

  var state = { q: '', cat: 'all', sort: 'usefulness', deep: false, hideKnown: false };

  /* ── known words (per-device, no account) ───────────────── */
  function getKnown() {
    try {
      var raw = JSON.parse(localStorage.getItem(KNOWN_KEY) || '[]');
      return raw instanceof Array ? new Set(raw) : new Set();
    } catch (e) {
      return new Set();
    }
  }

  function saveKnown(set) {
    try {
      localStorage.setItem(KNOWN_KEY, JSON.stringify(Array.from(set)));
    } catch (e) { /* private mode / quota — tracking is best-effort */ }
  }

  var known = getKnown();

  /* ── helpers ────────────────────────────────────────────── */
  function el2(tag, cls, text) {
    var n = document.createElement(tag);
    if (cls) n.className = cls;
    if (text != null) n.textContent = text;
    return n;
  }

  function catLabel(key) {
    return CAT_LABELS[key] || key.replace(/-/g, ' ');
  }

  /* Precomputed lowercase haystack so filtering never re-joins strings. */
  var haystack = Object.create(null);
  entries.forEach(function (e) {
    haystack[e.id] = [
      e.term, e.thai_script, e.literal_meaning, e.actual_meaning,
      e.usage_note, e.example_en, e.example_romanized, e.id,
      e.alt_thai, (e.alt_terms || []).join(' ')
    ].join(' ').toLowerCase();
  });

  /* Which text to voice for a word: an explicit speak_text override wins
     (e.g. "555" needs its Thai spelling-out, not the digits), else the
     Thai script. Example sentences have no override. The actual speaking
     lives in speak.js so every generated term page shares it. */
  function speakTextFor(e) {
    return e.speak_text || e.thai_script || '';
  }

  function speakButton(text, label, cls) {
    var b = el2('button', 'gl-iconbtn ' + (cls || ''), '\uD83D\uDD0A');
    b.type = 'button';
    b.setAttribute('data-speak', text);
    b.setAttribute('aria-label', label);
    b.title = label;
    b.disabled = true; /* speak.js enables it once a th-* voice is found */
    return b;
  }

  /* ── card rendering ─────────────────────────────────────── */
  function scoreRow(label, value) {
    var wrap = el2('span', 'gl-score');
    wrap.appendChild(el2('span', 'gl-score-label', label));
    var dots = el2('span', 'dots');
    dots.setAttribute('role', 'img');
    dots.setAttribute('aria-label', label + ' ' + value + ' of 5');
    for (var i = 1; i <= 5; i++) {
      var d = el2('span', 'dot' + (i <= value ? ' on' : ''));
      dots.appendChild(d);
    }
    wrap.appendChild(dots);
    return wrap;
  }

  function buildCard(e, visibleIds) {
    var card = el2('article', 'gl-card');
    card.id = e.id;
    card.setAttribute('data-id', e.id);
    if (known.has(e.id)) card.classList.add('known');

    /* head */
    var head = el2('header', 'gl-card-head');
    var term = el2('div', 'gl-term');

    /* The anchor wraps only the term name, so the whole card is clickable
       (via .gl-card-link::after) while the link's accessible name stays the
       term itself instead of duplicating the heading. */
    var name = el2('h3', 'gl-term-name');
    var link = el2('a', 'gl-card-link', e.term);
    link.href = 'terms/' + e.id + '.html';
    name.appendChild(link);
    term.appendChild(name);

    if (e.alt_terms && e.alt_terms.length) {
      term.appendChild(el2('span', 'gl-term-alt', 'also ' + e.alt_terms.join(', ')));
    }
    term.appendChild(el2('span', 'gl-term-thai', e.thai_script));
    if (e.alt_thai) term.appendChild(el2('span', 'gl-term-altthai', e.alt_thai));
    head.appendChild(term);

    var tools = el2('div', 'gl-card-tools');
    tools.appendChild(speakButton(speakTextFor(e), 'Hear ' + e.term, 'gl-speak'));
    head.appendChild(tools);
    card.appendChild(head);

    /* meta: category + the two independent score axes */
    var meta = el2('div', 'gl-meta');
    meta.appendChild(el2('span', 'gl-cat gl-cat--' + e.category, catLabel(e.category)));
    meta.appendChild(scoreRow('use', e.usefulness));
    meta.appendChild(scoreRow('slang', e.slanginess));
    card.appendChild(meta);

    if (e.literal_meaning && e.literal_meaning !== '\u2014') {
      card.appendChild(el2('p', 'gl-literal', 'Literally: ' + e.literal_meaning));
    }
    card.appendChild(el2('p', 'gl-meaning', e.actual_meaning));

    /* example sentence — inline only, no reveal interaction */
    var ex = el2('div', 'gl-example');
    ex.appendChild(el2('p', 'gl-ex-th', e.example_th));
    ex.appendChild(el2('p', 'gl-ex-rom', e.example_romanized));
    /* The example's speaker rides at the end of the English line: inline, so it
       can never overlap the Thai or romanization above it. */
    var exEn = el2('p', 'gl-ex-en', e.example_en);
    if (e.example_th) {
      exEn.appendChild(speakButton(e.example_th, 'Hear the example sentence', 'gl-speak-ex'));
      exEn.appendChild(document.createTextNode(' '));
    }
    ex.appendChild(exEn);
    card.appendChild(ex);

    if (e.usage_note) card.appendChild(el2('p', 'gl-note', e.usage_note));

    /* see also — jump to the card when it is on screen, else the static page */
    if (e.related && e.related.length) {
      var see = el2('p', 'gl-see');
      see.appendChild(el2('span', 'gl-see-label', 'See also \u00b7 '));
      e.related.forEach(function (rid, i) {
        var target = byId[rid];
        if (!target) return;
        if (i) see.appendChild(document.createTextNode(', '));
        var a = el2('a', null, target.term);
        a.href = visibleIds && visibleIds[rid] ? '#' + rid : 'terms/' + rid + '.html';
        see.appendChild(a);
      });
      card.appendChild(see);
    }

    /* foot */
    var foot = el2('footer', 'gl-card-foot');
    var label = el2('label', 'gl-toggle');
    var box = document.createElement('input');
    box.type = 'checkbox';
    box.checked = known.has(e.id);
    box.addEventListener('change', function () {
      if (box.checked) known.add(e.id); else known.delete(e.id);
      saveKnown(known);
      /* patch in place — a full re-render here would replay the entry animation */
      card.classList.toggle('known', box.checked);
      if (state.hideKnown) render();
    });
    label.appendChild(box);
    label.appendChild(document.createTextNode('I know this'));
    foot.appendChild(label);
    card.appendChild(foot);

    return card;
  }

  /* ── filter + sort ──────────────────────────────────────── */
  function select() {
    var out = [];
    for (var i = 0; i < entries.length; i++) {
      var e = entries[i];
      if (state.cat !== 'all' && e.category !== state.cat) continue;
      if (state.deep && e.slanginess < DEEP_CUT) continue;
      if (state.hideKnown && known.has(e.id)) continue;
      if (state.q && haystack[e.id].indexOf(state.q) === -1) continue;
      out.push(e);
    }

    if (state.sort === 'usefulness') {
      out.sort(function (a, b) {
        return (b.usefulness - a.usefulness) || a.term.localeCompare(b.term);
      });
    } else if (state.sort === 'slanginess') {
      out.sort(function (a, b) {
        return (b.slanginess - a.slanginess) || (b.usefulness - a.usefulness) ||
               a.term.localeCompare(b.term);
      });
    } else {
      out.sort(function (a, b) { return a.term.localeCompare(b.term); });
    }
    return out;
  }

  function render() {
    var list = select();

    var visible = Object.create(null);
    list.forEach(function (e) { visible[e.id] = true; });

    var frag = document.createDocumentFragment();
    list.forEach(function (e) { frag.appendChild(buildCard(e, visible)); });
    grid.replaceChildren(frag);

    /* Cards are rebuilt on every filter/sort/known toggle, so hand the fresh
       speak buttons back to speak.js to wire up (it de-dupes). */
    if (window.OA_SPEAK) window.OA_SPEAK.refresh();

    el.empty.hidden = list.length !== 0;
    el.count.textContent = list.length === entries.length
      ? entries.length + ' terms'
      : list.length + ' of ' + entries.length;
  }

  /* ── category tabs ──────────────────────────────────────── */
  function buildTabs() {
    var counts = Object.create(null);
    entries.forEach(function (e) { counts[e.category] = (counts[e.category] || 0) + 1; });

    var cats = Object.keys(counts).sort(function (a, b) { return counts[b] - counts[a]; });
    var keys = ['all'].concat(cats);

    keys.forEach(function (key) {
      var b = el2('button', 'gl-tab' + (key === state.cat ? ' active' : ''));
      b.type = 'button';
      b.setAttribute('data-cat', key);
      b.setAttribute('aria-pressed', key === state.cat ? 'true' : 'false');
      b.appendChild(document.createTextNode(key === 'all' ? 'All' : catLabel(key)));
      b.appendChild(el2('span', 'n', key === 'all' ? entries.length : counts[key]));
      b.addEventListener('click', function () {
        state.cat = key;
        Array.prototype.forEach.call(el.tabs.children, function (btn) {
          var on = btn.getAttribute('data-cat') === key;
          btn.classList.toggle('active', on);
          btn.setAttribute('aria-pressed', on ? 'true' : 'false');
        });
        render();
      });
      el.tabs.appendChild(b);
    });
  }

  /* ── word of the day (deterministic per UTC calendar day) ─ */
  function buildSotd() {
    var e = entries[Math.floor(Date.now() / 86400000) % entries.length];
    var body = el.sotd;
    var term = el2('span', 'gl-sotd-term', e.term);
    term.appendChild(el2('span', 'th', e.thai_script));
    body.appendChild(term);
    body.appendChild(el2('p', 'gl-sotd-def', e.actual_meaning));

    /* Whole banner is the link target, not just the word. */
    var link = el2('a', 'gl-sotd-link');
    link.href = 'terms/' + e.id + '.html';
    link.setAttribute('aria-label', 'Word of the day: ' + e.term + ' — open its page');
    body.appendChild(link);
  }

  /* ── wire up ────────────────────────────────────────────── */
  var timer = null;
  el.q.addEventListener('input', function () {
    var v = el.q.value.trim().toLowerCase();
    clearTimeout(timer);
    timer = setTimeout(function () { state.q = v; render(); }, DEBOUNCE_MS);
  });

  el.sort.addEventListener('change', function () { state.sort = el.sort.value; render(); });
  el.deep.addEventListener('change', function () { state.deep = el.deep.checked; render(); });
  el.hideKnown.addEventListener('change', function () {
    state.hideKnown = el.hideKnown.checked;
    render();
  });

  /* speak.js owns voice detection and the no-tts body class; it loads first. */
  buildTabs();
  buildSotd();
  render();
})();